package io.advantageous.reakt.exception;

public class ResultFailedException extends RuntimeException {

    public ResultFailedException(Throwable cause) {
        super(cause);
    }
}
